import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import President from "@/components/home/president/President";
import useFetch from "@/hooks/useFetch";
import HomeAdvisor from "@/components/home/homeAdvisor/HomeAdvisor";
import HomeCountUp from "@/components/home/homeCountUp/HomeCountUp";
import CarouselBanner from "@/components/home/carouselBanner/CarouselBanner";
import { Container, Row } from "react-bootstrap";
import CardDesign from "@/components/cardDesign/CardDesign";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data, loading } = useFetch("/member/csfdu/General");
  return (
    <>
      <Head>
        <title>Cox&apos;s Bazar Student Forum General</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./csfdu.jpeg" />
      </Head>
      <main>
        {loading ? (
          <div className="loadingContainer">
            <img src="./loading.gif" alt="" className="loadingGif" />
          </div>
        ) : (
          <>
            <div className="headerTitle mt-5">
              <h3 class="headerTitleMain">সাধারণ সদস্য</h3>
            </div>
            {/* Advisor Details */}
            <Container className="mt-4">
              <Row>
                {data?.data.map((item) => (
                  <CardDesign key={item.serial} item={item} />
                ))}
              </Row>
            </Container>
          </>
        )}
      </main>
    </>
  );
}
